local constants = {}

constants.INIT = "INIT"

constants.REFERENCE_SELECTION = "REFERENCE_SELECTION"
constants.PROTO_GROUP_SELECTION = "PROTO_GROUP_SELECTION"
constants.REFERENCE_CHANGE = "REFERENCE_CHANGE"
constants.REFERENCE_RESET = "REFERENCE_RESET"

constants.COLOR_CHANGE = "COLOR_CHANGE"
constants.STATION_CHANGE = "STATION_CHANGE"
constants.ALERT_MESSAGE_CHANGE = "ALERT_MESSAGE_CHANGE"

return constants
